### ISSUE TITLE
When player circle kill player circle.

### ISSUE THREAD

**Issue by imini-app** [imini-app/multiple-player-colyseus-matter-phaser#1]
```
trying to encode "NaN" in PlayerCircleSchema#hp
Error: a 'number' was expected, but 'undefined' was provided in PlayerCircleSchema#hp
    at new EncodeSchemaError (/usr/app/node_modules/@colyseus/schema/build/cjs/index.js:2232:42)
    at assertType (/usr/app/node_modules/@colyseus/schema/build/cjs/index.js:2266:15)
    at encodePrimitiveType (/usr/app/node_modules/@colyseus/schema/build/cjs/index.js:2275:5)
    at StateSchema.Schema.encode (/usr/app/node_modules/@colyseus/schema/build/cjs/index.js:2686:21)
    at SchemaSerializer.applyPatches (/usr/app/node_modules/@colyseus/core/build/serializer/SchemaSerializer.js:38:40)
    at GameRoom.broadcastPatch (/usr/app/node_modules/@colyseus/core/build/Room.js:210:45)
    at Timeout._onTimeout (/usr/app/node_modules/@colyseus/core/build/Room.js:116:58)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
Error: a 'number' was expected, but 'undefined' was provided in PlayerCircleSchema#hp
    at new EncodeSchemaError (/usr/app/node_modules/@colyseus/schema/build/cjs/index.js:2232:42)
    at assertType (/usr/app/node_modules/@colyseus/schema/build/cjs/index.js:2266:15)
    at encodePrimitiveType (/usr/app/node_modules/@colyseus/schema/build/cjs/index.js:2275:5)
    at StateSchema.Schema.encode (/usr/app/node_modules/@colyseus/schema/build/cjs/index.js:2686:21)
    at SchemaSerializer.applyPatches (/usr/app/node_modules/@colyseus/core/build/serializer/SchemaSerializer.js:38:40)
    at GameRoom.broadcastPatch (/usr/app/node_modules/@colyseus/core/build/Room.js:210:45)
    at Timeout._onTimeout (/usr/app/node_modules/@colyseus/core/build/Room.js:116:58)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
game server is going down.
```

**Comment by imini-app** [comment]
This is fixed in https://github.com/imini-app/multiple-player-colyseus-matter-phaser/commit/6ca04a1261c5bee05556cc5daabcb716620d7467
